######################################################################
# Automatically generated by qmake (3.1) Thu Dec 12 16:06:05 2019
######################################################################

TEMPLATE = subdirs

# Directories

OTHER_FILES += blue.css \
    black.css
